version: "3.8"
services:
  backend:
    command: dotnet QuizHub.Web.Api.dll
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80:80
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_hub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
